[package]
name = "rust-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.25.0"
rand = "0.8.5"
rfd = "0.12.1"
rodio = "0.17.3"
